name:                noobs-notification
version:             0.1.0
github: dogonthehorizon/noobs-notification
license:             BSD3
author:              Fernando Freire
copyright:           2019 Fernando Freire
extra-source-files:
- README.md

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing
  - -fno-warn-partial-type-signatures
  - -fwarn-incomplete-patterns
  - -fwarn-missing-signatures
  - -fwarn-tabs
  - -fwarn-unused-imports

# Needs to manually be kept in sync w/ .stylish-haskell.yaml
default-extensions:
  - BangPatterns
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables


dependencies:
  - base >= 4.7 && < 5
  - aeson
  - amazonka
  - text

library:
  source-dirs: src
  dependencies:
    - amazonka-core
    - amazonka-s3
    - basic-lens
    - conduit-extra
    - scalpel

executables:
  noobs-notification:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - noobs-notification
      - envy
      - hal
      - mtl
      - exceptions
