AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure for the NOOBS notification application.
Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: Enabled
