AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Infrastructure for the NOOBS notification application.
Parameters:
  NotificationEmailAddress:
    Description: The e-mail to send updates of new images to
    Type: String
Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: Enabled
  NoobsNotification:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: NOT_USED
      Runtime: provided
      CodeUri: ../.stack-work/docker/_home/.local/bin
      MemorySize: 128
      Timeout: 5
      Environment:
        Variables:
          NOOBS_BUCKET_NAME: !Ref ImageBucket
          NOTIFICATION_TOPIC: !Ref NotificationTopic
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - "s3:Put*"
                - "s3:Get*"
              Resource:
                - !Sub "arn:aws:s3:::${ImageBucket}/*"
            - Effect: Allow
              Action: "s3:List*"
              Resource:
                - !Sub "arn:aws:s3:::${ImageBucket}"
            - Effect: Allow
              Action: "sns:Publish"
              Resource:
                - !Ref NotificationTopic
  NotificationTopic:
    Type: AWS::SNS::Topic
  NotificationEmailSub:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref NotificationTopic
      Endpoint: !Ref NotificationEmailAddress
      Protocol: email
